version: '3.5'

services:
  
  postgres:
    image: postgres:13.7-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NoPassword1
    volumes:
      - postgres-integration-tests:/var/lib/postgresql/data
    networks:
      - togo-app-network-integration-tests

  togo.api.integration_tests:
    build:
      context: .
      dockerfile: Dockerfile.IntegrationTests
    depends_on:
      - postgres
    networks:
      - togo-app-network-integration-tests

volumes:
  postgres-integration-tests:
    driver: local

networks:
  togo-app-network-integration-tests:
    driver: bridge
