version: '3.5'

services:
  
  postgres:
    image: postgres:13.7-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NoPassword1
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - togo-app-network

  togo.api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - togo-app-network

volumes:
  postgres:
    driver: local

networks:
  togo-app-network:
    driver: bridge
